### ISSUE TITLE
!HOTFIX: 회원가입시 Username 한글으로 작성시 회원가입 완료되는 버그 발생

### ISSUE THREAD

**Issue by LeeHyunji** [sparta-B5/django-instagram-clone#19]
User 모델에서 회원가입시  username부분에서 한글로 작성해도 회원가입되는 버그가 발생했습니다.
username은 아이디와 같아서 영문, (_. 등 기본특수문자), 숫자 이렇게만 가능하도록 해야할것 같습니다.

**Comment by Choding91** [comment]
username 에도 정규식 추가하였습니다.
4~12 자리로 구성되어 있으며, 영문, 숫자, 영문+숫자 조합만 가능합니다.
