### ISSUE TITLE
!HOTFIX : signinsignup banch에서 어드민 계정이 실행되지 않습니다.

### ISSUE THREAD

**Issue by LeeHyunji** [sparta-B5/django-instagram-clone#9]
signinsignup 브런치 바탕으로 작업을 하려고하는데 어드민 계정이 생성 및 admin 페이지에 접속되지 않습니다!

**Comment by Choding91** [comment]
User(AbstractBaseUser) 사용 시 admin 포함 모든 user 필드 및 사이트를 직접 custom 해야 하는 문제 발생
User(AbstractUser) 로 변경하여 정규 필드 테이블 적용 / user_id > username

요약
AbstractUser : User 의 모든 기능을 포함한 기본 필드 테이블
AbstractBaseUser : User 의 최소 기능만 적용하여 자유로이 custom 가능한 필드 테이블
